import { randomBytes } from 'node:crypto';
import { join } from 'node:path';
import { userTokenLensDir } from '../shared/config.js';
import { pathExists, readJsonFileOrDefault, writeJsonFileAtomic } from '../shared/io.js';

/**
 * **Consent to contribute anonymous monthly aggregates.**
 *
 * ## Why this is not a config setting
 *
 * Everything else the user can change lives in `.tokenlens/config.json`,
 * which has a *project* layer. Consent must not: a repository could then
 * ship a config that opts its readers into sharing, and cloning it would be
 * enough. Consent is therefore machine-level only, in its own file, and the
 * project layer has no way to reach it.
 *
 * ## Why it records a version
 *
 * Consent is to a specific payload, not to the idea of sharing. If the
 * contribution gains a field, everyone who agreed to the previous shape has
 * not agreed to the new one — so {@link hasActiveConsent} refuses until they
 * are asked again. Without this, "opt in once" quietly becomes "opt in to
 * whatever we add later".
 *
 * ## Why the id is random
 *
 * `installId` elsewhere is a salted hash of a real path — pseudonymous, but
 * derived from something. A contributor id is generated from random bytes
 * instead, so it is correlated with nothing at all and can be discarded and
 * regenerated by deleting one file. It exists only to let the far end
 * de-duplicate two submissions for the same month.
 */
export const CONSENT_FILE_NAME = 'consent.json';

/** Bumped whenever the contribution payload changes shape. Invalidates prior consent. */
export const CONTRIBUTION_VERSION = 1;

export interface ConsentRecord {
  readonly contributionVersion: number;
  readonly contributorId: string;
  readonly consentedAt: string;
  /** Set when consent is withdrawn. The record is kept so the change is auditable. */
  readonly revokedAt?: string;
}

export function consentFilePath(): string {
  return join(userTokenLensDir(), CONSENT_FILE_NAME);
}

export async function readConsent(): Promise<ConsentRecord | undefined> {
  if (!(await pathExists(consentFilePath()))) return undefined;
  // A corrupt consent file must read as "no consent", never as consent.
  const record = await readJsonFileOrDefault<ConsentRecord | undefined>(
    consentFilePath(),
    undefined,
    { onParseError: 'warn' },
  );
  return record?.contributorId === undefined ? undefined : record;
}

export type ConsentState =
  | { readonly active: true; readonly record: ConsentRecord }
  | { readonly active: false; readonly reason: 'never-given' | 'revoked' | 'version-changed' };

/**
 * Whether sharing may happen right now.
 *
 * Fails closed in every ambiguous case: absent file, unreadable file,
 * withdrawn consent, or consent given to a payload shape that no longer
 * matches.
 */
export function consentState(record: ConsentRecord | undefined): ConsentState {
  if (record === undefined) return { active: false, reason: 'never-given' };
  if (record.revokedAt !== undefined) return { active: false, reason: 'revoked' };
  if (record.contributionVersion !== CONTRIBUTION_VERSION) {
    return { active: false, reason: 'version-changed' };
  }
  return { active: true, record };
}

export async function hasActiveConsent(): Promise<boolean> {
  return consentState(await readConsent()).active;
}

/**
 * Records consent, reusing the existing contributor id when there is one so
 * that opting out and back in does not look like a new participant.
 */
export async function grantConsent(now: Date = new Date()): Promise<ConsentRecord> {
  const existing = await readConsent();
  const record: ConsentRecord = {
    contributionVersion: CONTRIBUTION_VERSION,
    contributorId: existing?.contributorId ?? randomBytes(16).toString('hex'),
    consentedAt: now.toISOString(),
  };
  await writeJsonFileAtomic(consentFilePath(), record);
  return record;
}

export async function revokeConsent(now: Date = new Date()): Promise<ConsentRecord | undefined> {
  const existing = await readConsent();
  if (existing === undefined) return undefined;
  const record: ConsentRecord = { ...existing, revokedAt: now.toISOString() };
  await writeJsonFileAtomic(consentFilePath(), record);
  return record;
}

export const CONSENT_STATE_TEXT: Readonly<Record<string, string>> = {
  'never-given': 'Not sharing. Nothing has ever been written to the outbox.',
  revoked: 'Sharing was turned off. Nothing new will be produced.',
  'version-changed':
    'What would be shared has changed since you agreed to it, so sharing is paused until you review the new payload and agree again.',
};
