import { GUARDS, UNAVAILABLE_GUARDS } from './guards.js';
import { HOOK_EVENTS, type HookEvent } from './protocol.js';
import { VERSION } from '../version.js';

/**
 * Generating the configuration that makes the agent call this binary.
 *
 * ## A repo commit is a deployment
 *
 * That is the whole appeal of hooks, and the whole risk. Dropping JSON at
 * `.github/hooks/` turns every developer who opens the repository into a
 * user of these guards, with no install, no marketplace review and no
 * approval step. So the generated file explains itself, names the binary
 * plainly, and is emitted to a directory rather than written into place —
 * the same rule D5 follows for policy artefacts.
 */
export type HookScope =
  /** `.github/hooks/` — committed, applies to everyone who opens the repo. */
  | 'workspace'
  /** `~/.copilot/hooks/` — this machine only. */
  | 'user';

export interface HookConfigArtefact {
  readonly path: string;
  readonly contents: string;
  readonly description: string;
}

/** Events a guard is actually registered for, so nothing is configured for nothing. */
function activeEvents(): HookEvent[] {
  const wanted = new Set<HookEvent>();
  for (const guard of GUARDS) for (const event of guard.events) wanted.add(event);
  // `PostToolUse` also drives the counters even where no guard fires on it.
  wanted.add('PostToolUse');
  wanted.add('SessionStart');
  return HOOK_EVENTS.filter((event) => wanted.has(event));
}

export interface HookConfigOptions {
  readonly scope?: HookScope;
  /** How the agent should invoke TokenLens. */
  readonly command?: string;
}

export function generateHookConfig(options: HookConfigOptions = {}): HookConfigArtefact[] {
  const scope = options.scope ?? 'workspace';
  const command = options.command ?? 'tokenlens';
  const directory = scope === 'workspace' ? '.github/hooks' : 'copilot-hooks';

  const hooks = activeEvents().map((event) => ({
    event,
    command: `${command} hook --event ${event}`,
    // Comfortably inside the p99 budget, and short enough that a wedged
    // hook cannot stall a tool call for long.
    timeoutMs: 5000,
  }));

  const document = {
    $comment: [
      `Generated by TokenLens ${VERSION}.`,
      'Each entry runs the TokenLens binary as a subprocess: JSON in on stdin, one decision out on stdout.',
      'Every failure path inside the hook returns {"continue":true}, so a broken guard cannot break the agent.',
      'Remove this file to disable every guard at once.',
    ],
    version: 1,
    hooks,
  };

  return [
    {
      path: `${directory}/tokenlens.json`,
      contents: `${JSON.stringify(document, null, 2)}\n`,
      description:
        scope === 'workspace'
          ? 'Committed to the repository — applies to everyone who opens it'
          : 'This machine only — copy to ~/.copilot/hooks/',
    },
    {
      path: `${directory}/README.md`,
      contents: renderReadme(scope, command),
      description: 'What each guard does, what it costs, and how to turn one off',
    },
  ];
}

function renderReadme(scope: HookScope, command: string): string {
  const rows = GUARDS.map(
    (guard) =>
      `| \`${guard.id}\` | ${guard.automation} | ${guard.attacks} | ${guard.events.join(', ')} |`,
  ).join('\n');

  const unavailable = UNAVAILABLE_GUARDS.map(
    (entry) =>
      `- **${entry.automation} ${entry.name}** — ${entry.reason}\n  - Unblocked by: ${entry.unblockedBy}`,
  ).join('\n');

  return `# TokenLens runtime guards

Generated by TokenLens ${VERSION}. Scope: **${scope}**.

These are Tier B controls: deterministic interception at the moment of spend. They are **optional by
design** — Tier A configuration alone delivers most of the available saving, and an organisation can
disable hooks entirely through \`ChatHooks\`.

## What is enabled

| Guard | Automation | Attacks | Events |
|---|---|---|---|
${rows}

## What it will not do

- **It never denies on a guess.** A read is suppressed only when the file's content hash is
  *identical* to the copy already in the conversation. Change one byte and the read goes through.
  Anything unprovable — a file too large to hash, a path outside the workspace, an unreadable file —
  is allowed.
- **It never breaks the agent.** Every failure path returns \`{"continue":true}\`. A guard that throws
  is skipped; a state store that will not open is skipped; an unparseable payload is allowed.
- **It never calls the network or a model.** Enforced by an architectural import test, not a promise.
- **A rule that misfires turns itself off.** If interventions are being worked around, the rule stands
  itself down and says so, rather than have you disable every guard at once.

## Turning things off

\`\`\`sh
${command} hook status              # what fired, what was reversed, what is disabled
${command} hook disable payload-guard
${command} hook enable payload-guard
\`\`\`

Or delete this directory, which removes every guard at once.

## Specified but not built
${unavailable.length > 0 ? `\n${unavailable}\n` : '\nNothing.\n'}`;
}
