import { randomUUID } from 'node:crypto';
import { DEFAULT_MODEL_CAVEAT, type ResolvedSetting } from './keys.js';
import { VERSION } from '../version.js';
import type { PriorDocument } from './channel.js';

export type { PriorDocument };

export type SettingValue = string | number | boolean | Record<string, boolean>;

export interface Artefact {
  /** Path relative to the output directory. Always POSIX-separated. */
  readonly path: string;
  readonly contents: string;
  readonly description: string;
  /** `apply` deploys the policy; `rollback` returns the machine to what was there before. */
  readonly role: 'apply' | 'rollback';
}

/**
 * What a value was before, so an inverse can be generated. `undefined`
 * means the setting was not set at all, and its rollback is a deletion
 * rather than a restoration — a distinction that matters, because writing
 * back an assumed default is not the same as removing the key.
 */
export type PriorValues = Readonly<Record<string, string | undefined>>;

const WINDOWS_POLICY_KEY = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\GitHubCopilot';
const MACOS_DOMAIN = 'com.github.copilot';

function header(what: string): string {
  return (
    `Generated by TokenLens ${VERSION}. ${what}\n` +
    'Every value here is traceable to a measured figure — run `tokenlens policy emit --dry-run` ' +
    'to see the credits attributed to each line.'
  );
}

// ---------------------------------------------------------------------------
// Windows — registry
// ---------------------------------------------------------------------------

/** `.reg` escaping: backslashes and quotes, in that order. */
function regString(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/**
 * `.reg` files are consumed by `reg import`, which reads a UTF-8 file
 * without a BOM as ANSI. The typographic characters this project uses
 * elsewhere in its prose — `·`, `—`, `’` — therefore arrive mangled, in a
 * file whose whole purpose is to be pasted into a production MDM policy.
 *
 * Comments are transliterated to ASCII rather than the file being written
 * as UTF-16, because a plain ASCII `.reg` is readable by every tool that
 * has ever consumed one, and the prose loses nothing that matters.
 */
function ascii(text: string): string {
  return text
    .replace(/[·•]/g, '-')
    .replace(/[—–]/g, '-')
    .replace(/[’‘]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/…/g, '...')
    .replace(/[^\x20-\x7e]/g, '');
}

function regValue(value: SettingValue): string {
  if (typeof value === 'boolean') return `dword:${(value ? 1 : 0).toString(16).padStart(8, '0')}`;
  if (typeof value === 'number') return `dword:${Math.trunc(value).toString(16).padStart(8, '0')}`;
  if (typeof value === 'string') return regString(value);
  // Objects have no registry representation; managed settings never carry one.
  return regString(JSON.stringify(value));
}

export function emitWindowsRegistry(
  settings: readonly ResolvedSetting[],
  prior: PriorValues = {},
): Artefact[] {
  const managed = settings.filter((setting) => setting.key.managedName !== undefined);
  if (managed.length === 0) return [];

  const lines = [
    'Windows Registry Editor Version 5.00',
    '',
    // Split before transliterating: `ascii` strips control characters, so
    // running it over a multi-line string first would swallow the newline
    // and weld two comment lines together.
    ...header('Deploy with `reg import`, or paste into an Intune settings-catalog policy.')
      .split('\n')
      .map((line) => `; ${ascii(line)}`),
    `; ${ascii(DEFAULT_MODEL_CAVEAT)}`,
    '',
    `[${WINDOWS_POLICY_KEY}]`,
    ...managed.map(
      (setting) =>
        `${regString(setting.key.managedName ?? '')}=${regValue(setting.value)}` +
        ascii(`  ; ${setting.key.auto} · attacks ${setting.key.attacks} · from ${setting.from}`),
    ),
    '',
  ];

  // A value that was not there before is removed by `=-`; one that was
  // there is written back verbatim. Guessing a default would leave the
  // machine in a state it was never in.
  const rollbackLines = [
    'Windows Registry Editor Version 5.00',
    '',
    `; ${ascii(header('Undoes the policy emitted alongside it.').split('\n')[0] ?? '')}`,
    '',
    `[${WINDOWS_POLICY_KEY}]`,
    ...managed.map((setting) => {
      const name = setting.key.managedName ?? '';
      const before = prior[name];
      return before === undefined
        ? `${regString(name)}=-  ; was not set before`
        : `${regString(name)}=${regString(before)}  ; restored`;
    }),
    '',
  ];

  return [
    {
      path: 'windows/GitHubCopilot.reg',
      contents: lines.join('\r\n'),
      description: `Windows registry policy — ${String(managed.length)} value(s) under ${WINDOWS_POLICY_KEY}`,
      role: 'apply',
    },
    {
      path: 'windows/GitHubCopilot.rollback.reg',
      contents: rollbackLines.join('\r\n'),
      description: 'One-command rollback: `reg import GitHubCopilot.rollback.reg`',
      role: 'rollback',
    },
    {
      path: 'windows/intune-settings.json',
      contents: `${JSON.stringify(
        {
          $comment: header('Descriptor for an Intune settings-catalog policy.').split('\n'),
          registryKey: WINDOWS_POLICY_KEY,
          values: managed.map((setting) => ({
            name: setting.key.managedName,
            type: typeof setting.value === 'string' ? 'REG_SZ' : 'REG_DWORD',
            value: setting.value,
            automation: setting.key.auto,
            from: setting.from,
          })),
        },
        null,
        2,
      )}\n`,
      description: 'Intune-ready descriptor of the same values (not a signed .intunewin package)',
      role: 'apply',
    },
  ];
}

// ---------------------------------------------------------------------------
// macOS — configuration profile
// ---------------------------------------------------------------------------

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function plistValue(value: SettingValue): string {
  if (typeof value === 'boolean') return value ? '<true/>' : '<false/>';
  if (typeof value === 'number') return `<integer>${String(Math.trunc(value))}</integer>`;
  if (typeof value === 'string') return `<string>${xmlEscape(value)}</string>`;
  return `<string>${xmlEscape(JSON.stringify(value))}</string>`;
}

export interface MacosEmitOptions {
  /**
   * Injected so a generated profile is byte-identical across runs. Apple
   * requires a UUID per payload; deriving it from the content rather than
   * randomly is what makes `emit.idempotent.test.ts` meaningful.
   */
  readonly uuid?: () => string;
}

export function emitMacosProfile(
  settings: readonly ResolvedSetting[],
  options: MacosEmitOptions = {},
): Artefact[] {
  const managed = settings.filter((setting) => setting.key.managedName !== undefined);
  if (managed.length === 0) return [];

  const uuid = options.uuid ?? randomUUID;
  const payloadUuid = uuid();
  const profileUuid = uuid();

  const entries = managed
    .map(
      (setting) =>
        `          <key>${xmlEscape(setting.key.managedName ?? '')}</key>\n` +
        `          ${plistValue(setting.value)}`,
    )
    .join('\n');

  const contents = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
${xmlEscape(header('Deploy with Jamf, Intune for macOS, or any MDM that accepts a .mobileconfig.'))}
${xmlEscape(DEFAULT_MODEL_CAVEAT)}
-->
<plist version="1.0">
<dict>
  <key>PayloadContent</key>
  <array>
    <dict>
      <key>PayloadType</key>
      <string>com.apple.ManagedClient.preferences</string>
      <key>PayloadVersion</key>
      <integer>1</integer>
      <key>PayloadIdentifier</key>
      <string>${MACOS_DOMAIN}.tokenlens</string>
      <key>PayloadUUID</key>
      <string>${payloadUuid}</string>
      <key>PayloadDisplayName</key>
      <string>GitHub Copilot managed settings</string>
      <key>PayloadContent</key>
      <dict>
        <key>${MACOS_DOMAIN}</key>
        <dict>
          <key>Forced</key>
          <array>
            <dict>
              <key>mcx_preference_settings</key>
              <dict>
${entries}
              </dict>
            </dict>
          </array>
        </dict>
      </dict>
    </dict>
  </array>
  <key>PayloadType</key>
  <string>Configuration</string>
  <key>PayloadVersion</key>
  <integer>1</integer>
  <key>PayloadIdentifier</key>
  <string>${MACOS_DOMAIN}.tokenlens.profile</string>
  <key>PayloadUUID</key>
  <string>${profileUuid}</string>
  <key>PayloadDisplayName</key>
  <string>TokenLens \u2014 Copilot cost policy</string>
  <key>PayloadRemovalDisallowed</key>
  <false/>
</dict>
</plist>
`;

  return [
    {
      path: 'macos/GitHubCopilot.mobileconfig',
      contents,
      description: `macOS configuration profile — ${String(managed.length)} value(s) in the ${MACOS_DOMAIN} domain`,
      role: 'apply',
    },
    {
      path: 'macos/rollback.sh',
      contents:
        `#!/bin/sh\n# ${header('Removes the profile emitted alongside it.').split('\n')[0] ?? ''}\n` +
        `# PayloadRemovalDisallowed is false, so the profile can simply be removed.\n` +
        `sudo profiles remove -identifier ${MACOS_DOMAIN}.tokenlens.profile\n`,
      description: 'One-command rollback: `sh rollback.sh`',
      role: 'rollback',
    },
  ];
}

// ---------------------------------------------------------------------------
// File-based — managed-settings.json
// ---------------------------------------------------------------------------

export function emitManagedJson(
  settings: readonly ResolvedSetting[],
  prior: PriorDocument,
): Artefact[] {
  const managed = settings.filter((setting) => setting.key.managedName !== undefined);
  if (managed.length === 0 || prior.state === 'unreadable') return [];

  const priorDocument = prior.state === 'present' ? prior.document : undefined;
  const desired: Record<string, unknown> = { ...priorDocument };
  for (const setting of managed) desired[setting.key.managedName ?? ''] = setting.value;

  const artefacts: Artefact[] = [
    {
      path: 'file-based/managed-settings.json',
      contents: `${JSON.stringify(sortKeys(desired), null, 2)}\n`,
      description: `managed-settings.json — ${String(managed.length)} policy value(s), merged over what was already there`,
      role: 'apply',
    },
  ];

  artefacts.push(
    priorDocument === undefined
      ? {
          path: 'file-based/rollback.md',
          contents:
            '# Rollback\n\nThere was no `managed-settings.json` before this policy was emitted.\n' +
            'To roll back, delete the file at the platform path.\n',
          description: 'Rollback: delete the file (it did not exist before)',
          role: 'rollback',
        }
      : {
          path: 'file-based/managed-settings.rollback.json',
          contents: `${JSON.stringify(sortKeys(priorDocument), null, 2)}\n`,
          description: 'Rollback: the exact document that was there before',
          role: 'rollback',
        },
  );

  return artefacts;
}

// ---------------------------------------------------------------------------
// Workspace settings
// ---------------------------------------------------------------------------

export function emitWorkspaceSettings(
  settings: readonly ResolvedSetting[],
  prior: PriorDocument,
): Artefact[] {
  const workspace = settings.filter(
    (setting) => setting.key.surface === 'workspace' && setting.key.settingId !== undefined,
  );
  if (workspace.length === 0 || prior.state === 'unreadable') return [];

  const priorDocument = prior.state === 'present' ? prior.document : undefined;
  const desired: Record<string, unknown> = { ...priorDocument };
  for (const setting of workspace) {
    const id = setting.key.settingId ?? '';
    const existing = priorDocument?.[id];
    // `search.exclude` is merged rather than replaced: the repo's existing
    // exclusions are a deliberate choice and this policy is additive to them.
    desired[id] =
      id === 'search.exclude' && isRecord(existing)
        ? { ...existing, ...(setting.value as object) }
        : setting.value;
  }

  const artefacts: Artefact[] = [
    {
      path: 'workspace/settings.json',
      contents: `${JSON.stringify(sortKeys(desired), null, 2)}\n`,
      description: `.vscode/settings.json — ${String(workspace.length)} setting(s), merged over what was already there`,
      role: 'apply',
    },
  ];

  artefacts.push(
    priorDocument === undefined
      ? {
          path: 'workspace/rollback.md',
          contents:
            '# Rollback\n\nThere was no `.vscode/settings.json` before this policy was emitted.\n' +
            'To roll back, delete the file.\n',
          description: 'Rollback: delete the file (it did not exist before)',
          role: 'rollback',
        }
      : {
          path: 'workspace/settings.rollback.json',
          contents: `${JSON.stringify(sortKeys(priorDocument), null, 2)}\n`,
          description: 'Rollback: the exact document that was there before',
          role: 'rollback',
        },
  );

  return artefacts;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** Key order is normalised so re-emitting an unchanged policy produces no diff. */
function sortKeys(document: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(Object.entries(document).sort(([a], [b]) => a.localeCompare(b)));
}
